### PR TITLE
Windows path suport

### PR DESCRIPTION
**Pull request by bojan88**
Please check the second commit. The first is just white space removal done by my editor

### CODE REVIEW

**Comment by bojan88** [comment]
But why the tests are failing now?

**Comment by zxqfox** [comment]
because you have a bug ;-) for node 0.6

**Comment by bojan88** [comment]
Better question is how it passed before the last commit. Can you tell what's the bug? I don't have version 6 on `n` version manager.

**Comment by zxqfox** [comment]
node 0.6 doesn't have path.sep. https://github.com/WebReflection/dblite/commit/12e2046ef9881e9bb63398ed2776444a5b87a8cc#diff-81eaa31b90e40b1df2dd12739a3cba98R55

**Comment by kaelzhang** [comment]
Thanks a million for all the efforts of you two guys.

@bojan88 And could you plz implement `PATH_SEP` for node <= 0.6 ?

**Comment by bojan88** [comment]
Build is passing, but the tests are failing on WIndows

**Comment by kaelzhang** [comment]
Thanks @bojan88 @zxqfox 

I'll merge it first, then let me do the rest

**Pull request merged**
